### Coursera Applied Data Science Capstone - Weeks 4 & 5 - Analyze Chicago Communities to Open Boutique Donut Shop

This first section will install & import initial libraries and programs used in this Notebook 

In [2]:
import numpy as np # library to handle data in a vectorized manner

In [3]:
import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
import json # library to handle JSON files

In [5]:
!pip install geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
print('imported.')


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --yes
imported.


In [6]:
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

In [7]:
# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

In [8]:
# import k-means from clustering stage
from sklearn.cluster import KMeans

In [9]:
!pip install folium # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library
print('imported.')

     |████████████████████████████████| 102kB 9.3MB/s ta 0:00:011
imported.


This next section will read the Wikipedia page containing the Chicago communiities, pull it into a dataframe, and clean the table

In [10]:
df=pd.read_html("https://en.wikipedia.org/wiki/Community_areas_in_Chicago")[0]

In [11]:
df

Number[8]                 Name[8]  2017[9] Area (sq mi.)[10]  Area (km2)  \
0         01             Rogers Park    55062              1.84        4.77   
1         02              West Ridge    76215              3.53        9.14   
2         03                  Uptown    57973              2.32        6.01   
3         04          Lincoln Square    41715              2.56        6.63   
4         05            North Center    35789              2.05        5.31   
5         06               Lake View   100470              3.12        8.08   
6         07            Lincoln Park    67710              3.16        8.18   
7         08         Near North Side    88893              2.74        7.10   
8         09             Edison Park    11605              1.13        2.93   
9         10            Norwood Park    37089              4.37       11.32   
10        11          Jefferson Park    26808              2.33        6.03   
11        12             Forest Glen    19019              3.20        8.29   
12        13              North Park    18842              2.52        6.53   
13        14             Albany Park    51992              1.92        4.97   
14        15            Portage Park    64307              3.95       10.23   
15        16             Irving Park    54606              3.21        8.31   
16        17                 Dunning    43689              3.72        9.63   
17        18               Montclare    13830              0.99        2.56   
18        19          Belmont Cragin    79910              3.91       10.13   
19        20                 Hermosa    24144              1.17        3.03   
20        21                Avondale    37368              1.98        5.13   
21        22            Logan Square    73046              3.59        9.30   
22        23           Humboldt Park    56427              3.60        9.32   
23        24               West Town    84502              4.58       11.86   
24        25                  Austin    95260              7.15       18.52   
25        26      West Garfield Park    17163              1.28        3.32   
26        27      East Garfield Park    19996              1.93        5.00   
27        28          Near West Side    62872              5.69       14.74   
28        29          North Lawndale    35947              3.21        8.31   
29        30          South Lawndale    74851              4.59       11.89   
30        31         Lower West Side    32888              2.93        7.59   
31        32          (The) Loop[11]    35880              1.65        4.27   
32        33         Near South Side    23620              1.78        4.61   
33        34           Armour Square    13455              1.00        2.59   
34        35                 Douglas    20781              1.65        4.27   
35        36                 Oakland     6645              0.58        1.50   
36        37             Fuller Park     2439              0.71        1.84   
37        38         Grand Boulevard    22313              1.74        4.51   
38        39                 Kenwood    17189              1.04        2.69   
39        40         Washington Park    11502              1.52        3.94   
40        41               Hyde Park    26827              1.61        4.17   
41        42                Woodlawn    23268              2.07        5.36   
42        43             South Shore    50418              2.93        7.59   
43        44                 Chatham    31120              2.95        7.64   
44        45             Avalon Park     9985              1.25        3.24   
45        46           South Chicago    28263              3.34        8.65   
46        47                Burnside     2254              0.61        1.58   
47        48         Calumet Heights    13188              1.75        4.53   
48        49                Roseland    42433              4.82       12.48   
49        50                 Pullman     6613        

In looking at the initial dataframe, I see I can delete the "Number[8]" column since it contains the same valus as the index column. I can also delete the "Area (km2)" and "2017density (/km2)" columns since comparable columns based on square miles are also provided which is more predominently used in the United States. 

In [12]:
chi = df.drop('Number[8]', 1)
chi

Name[8]  2017[9] Area (sq mi.)[10]  Area (km2)  \
0              Rogers Park    55062              1.84        4.77   
1               West Ridge    76215              3.53        9.14   
2                   Uptown    57973              2.32        6.01   
3           Lincoln Square    41715              2.56        6.63   
4             North Center    35789              2.05        5.31   
5                Lake View   100470              3.12        8.08   
6             Lincoln Park    67710              3.16        8.18   
7          Near North Side    88893              2.74        7.10   
8              Edison Park    11605              1.13        2.93   
9             Norwood Park    37089              4.37       11.32   
10          Jefferson Park    26808              2.33        6.03   
11             Forest Glen    19019              3.20        8.29   
12              North Park    18842              2.52        6.53   
13             Albany Park    51992              1.92        4.97   
14            Portage Park    64307              3.95       10.23   
15             Irving Park    54606              3.21        8.31   
16                 Dunning    43689              3.72        9.63   
17               Montclare    13830              0.99        2.56   
18          Belmont Cragin    79910              3.91       10.13   
19                 Hermosa    24144              1.17        3.03   
20                Avondale    37368              1.98        5.13   
21            Logan Square    73046              3.59        9.30   
22           Humboldt Park    56427              3.60        9.32   
23               West Town    84502              4.58       11.86   
24                  Austin    95260              7.15       18.52   
25      West Garfield Park    17163              1.28        3.32   
26      East Garfield Park    19996              1.93        5.00   
27          Near West Side    62872              5.69       14.74   
28          North Lawndale    35947              3.21        8.31   
29          South Lawndale    74851              4.59       11.89   
30         Lower West Side    32888              2.93        7.59   
31          (The) Loop[11]    35880              1.65        4.27   
32         Near South Side    23620              1.78        4.61   
33           Armour Square    13455              1.00        2.59   
34                 Douglas    20781              1.65        4.27   
35                 Oakland     6645              0.58        1.50   
36             Fuller Park     2439              0.71        1.84   
37         Grand Boulevard    22313              1.74        4.51   
38                 Kenwood    17189              1.04        2.69   
39         Washington Park    11502              1.52        3.94   
40               Hyde Park    26827              1.61        4.17   
41                Woodlawn    23268              2.07        5.36   
42             South Shore    50418              2.93        7.59   
43                 Chatham    31120              2.95        7.64   
44             Avalon Park     9985              1.25        3.24   
45           South Chicago    28263              3.34        8.65   
46                Burnside     2254              0.61        1.58   
47         Calumet Heights    13188              1.75        4.53   
48                Roseland    42433              4.82       12.48   
49                 Pullman     6613              2.12        5.49   
50           South Deering    14614             10.90       28.23   
51               East Side    23737              2.98        7.72   
52            West Pullman    27742              3.56        9.22   
53               Riverdale     7394              3.53        9.14   
54               Hegewisch     9418              5.24       13.57   
55          Garfield Ridge    36396              4.23       10.96   
56          Archer Heights    13142              2.01        5.21   
57           Brig

In [13]:
chi = chi.drop ('Area (km2)', 1)
chi

Name[8]  2017[9] Area (sq mi.)[10]  2017density (/sq mi.)  \
0              Rogers Park    55062              1.84               29925.00   
1               West Ridge    76215              3.53               21590.65   
2                   Uptown    57973              2.32               24988.36   
3           Lincoln Square    41715              2.56               16294.92   
4             North Center    35789              2.05               17458.05   
5                Lake View   100470              3.12               32201.92   
6             Lincoln Park    67710              3.16               21427.22   
7          Near North Side    88893              2.74               32442.70   
8              Edison Park    11605              1.13                4235.40   
9             Norwood Park    37089              4.37                8487.19   
10          Jefferson Park    26808              2.33               11505.58   
11             Forest Glen    19019              3.20                5943.44   
12              North Park    18842              2.52                7476.98   
13             Albany Park    51992              1.92               27079.17   
14            Portage Park    64307              3.95               16280.25   
15             Irving Park    54606              3.21               17011.21   
16                 Dunning    43689              3.72               11744.35   
17               Montclare    13830              0.99               13969.70   
18          Belmont Cragin    79910              3.91               20437.34   
19                 Hermosa    24144              1.17               20635.90   
20                Avondale    37368              1.98               18872.73   
21            Logan Square    73046              3.59               20347.08   
22           Humboldt Park    56427              3.60               15674.17   
23               West Town    84502              4.58               18450.22   
24                  Austin    95260              7.15               13323.08   
25      West Garfield Park    17163              1.28               13408.59   
26      East Garfield Park    19996              1.93               10360.62   
27          Near West Side    62872              5.69               11049.56   
28          North Lawndale    35947              3.21               11198.44   
29          South Lawndale    74851              4.59               16307.41   
30         Lower West Side    32888              2.93               11224.57   
31          (The) Loop[11]    35880              1.65               21745.45   
32         Near South Side    23620              1.78               13269.66   
33           Armour Square    13455              1.00               13455.00   
34                 Douglas    20781              1.65               12594.55   
35                 Oakland     6645              0.58               11456.90   
36             Fuller Park     2439              0.71                3435.21   
37         Grand Boulevard    22313              1.74               12823.56   
38                 Kenwood    17189              1.04               16527.88   
39         Washington Park    11502              1.52                7567.11   
40               Hyde Park    26827              1.61               16662.73   
41                Woodlawn    23268              2.07               11240.58   
42             South Shore    50418              2.93               17207.51   
43                 Chatham    31120              2.95               10549.15   
44             Avalon Park     9985              1.25                7988.00   
45           South Chicago    28263              3.34                8461.98   
46                Burnside     2254              0.61                3695.08   
47         Calumet Heights    13188              1.75                7536.00   
48                Roseland    42433              4.82                8803.53   
49                 

In [14]:
chi = chi.drop('2017density (/km2)', 1)
chi

Name[8]  2017[9] Area (sq mi.)[10]  2017density (/sq mi.)
0              Rogers Park    55062              1.84               29925.00
1               West Ridge    76215              3.53               21590.65
2                   Uptown    57973              2.32               24988.36
3           Lincoln Square    41715              2.56               16294.92
4             North Center    35789              2.05               17458.05
5                Lake View   100470              3.12               32201.92
6             Lincoln Park    67710              3.16               21427.22
7          Near North Side    88893              2.74               32442.70
8              Edison Park    11605              1.13                4235.40
9             Norwood Park    37089              4.37                8487.19
10          Jefferson Park    26808              2.33               11505.58
11             Forest Glen    19019              3.20                5943.44
12              North Park    18842              2.52                7476.98
13             Albany Park    51992              1.92               27079.17
14            Portage Park    64307              3.95               16280.25
15             Irving Park    54606              3.21               17011.21
16                 Dunning    43689              3.72               11744.35
17               Montclare    13830              0.99               13969.70
18          Belmont Cragin    79910              3.91               20437.34
19                 Hermosa    24144              1.17               20635.90
20                Avondale    37368              1.98               18872.73
21            Logan Square    73046              3.59               20347.08
22           Humboldt Park    56427              3.60               15674.17
23               West Town    84502              4.58               18450.22
24                  Austin    95260              7.15               13323.08
25      West Garfield Park    17163              1.28               13408.59
26      East Garfield Park    19996              1.93               10360.62
27          Near West Side    62872              5.69               11049.56
28          North Lawndale    35947              3.21               11198.44
29          South Lawndale    74851              4.59               16307.41
30         Lower West Side    32888              2.93               11224.57
31          (The) Loop[11]    35880              1.65               21745.45
32         Near South Side    23620              1.78               13269.66
33           Armour Square    13455              1.00               13455.00
34                 Douglas    20781              1.65               12594.55
35                 Oakland     6645              0.58               11456.90
36             Fuller Park     2439              0.71                3435.21
37         Grand Boulevard    22313              1.74               12823.56
38                 Kenwood    17189              1.04               16527.88
39         Washington Park    11502              1.52                7567.11
40               Hyde Park    26827              1.61               16662.73
41                Woodlawn    23268              2.07               11240.58
42             South Shore    50418              2.93               17207.51
43                 Chatham    31120              2.95               10549.15
44             Avalon Park     9985              1.25                7988.00
45           South Chicago    28263              3.34                8461.98
46                Burnside     2254              0.61                3695.08
47         Calumet Heights    13188              1.75                7536.00
48                Roseland    42433              4.82                8803.53
49                 Pullman     6613              2.12                3119.34
50           South Deering    14614             10.90                1340.73
51             

Next, I will update the column names to something more useful

In [15]:
chi_clean1 = chi.rename(columns={"Name[8]": "Community", "2017[9]": "2017 Population", "Area (sq mi.)[10]": "Area (sq mi)", "2017density (/sq mi.)": "2017 Population Density (/sq mi)"})
chi_clean1   

Community  2017 Population Area (sq mi)  \
0              Rogers Park            55062         1.84   
1               West Ridge            76215         3.53   
2                   Uptown            57973         2.32   
3           Lincoln Square            41715         2.56   
4             North Center            35789         2.05   
5                Lake View           100470         3.12   
6             Lincoln Park            67710         3.16   
7          Near North Side            88893         2.74   
8              Edison Park            11605         1.13   
9             Norwood Park            37089         4.37   
10          Jefferson Park            26808         2.33   
11             Forest Glen            19019         3.20   
12              North Park            18842         2.52   
13             Albany Park            51992         1.92   
14            Portage Park            64307         3.95   
15             Irving Park            54606         3.21   
16                 Dunning            43689         3.72   
17               Montclare            13830         0.99   
18          Belmont Cragin            79910         3.91   
19                 Hermosa            24144         1.17   
20                Avondale            37368         1.98   
21            Logan Square            73046         3.59   
22           Humboldt Park            56427         3.60   
23               West Town            84502         4.58   
24                  Austin            95260         7.15   
25      West Garfield Park            17163         1.28   
26      East Garfield Park            19996         1.93   
27          Near West Side            62872         5.69   
28          North Lawndale            35947         3.21   
29          South Lawndale            74851         4.59   
30         Lower West Side            32888         2.93   
31          (The) Loop[11]            35880         1.65   
32         Near South Side            23620         1.78   
33           Armour Square            13455         1.00   
34                 Douglas            20781         1.65   
35                 Oakland             6645         0.58   
36             Fuller Park             2439         0.71   
37         Grand Boulevard            22313         1.74   
38                 Kenwood            17189         1.04   
39         Washington Park            11502         1.52   
40               Hyde Park            26827         1.61   
41                Woodlawn            23268         2.07   
42             South Shore            50418         2.93   
43                 Chatham            31120         2.95   
44             Avalon Park             9985         1.25   
45           South Chicago            28263         3.34   
46                Burnside             2254         0.61   
47         Calumet Heights            13188         1.75   
48                Roseland            42433         4.82   
49                 Pullman             6613         2.12   
50           South Deering            14614        10.90   
51               East Side            23737         2.98   
52            West Pullman            27742         3.56   
53               Riverdale             7394         3.53   
54               Hegewisch             9418         5.24   
55          Garfield Ridge            36396         4.23   
56          Archer Heights            13142         2.01   
57           Brighton Park            44813         2.72   
58           McKinley Park            15767         1.41   
59              Bridgeport            33637         2.09   
60                New City            39561         4.83   
61             West Elsdon            19237         1.17   
62               Gage Park            40873         2.20   
63                Clearing            25891         2.55   
64               West Lawn            33108         2.95   
65            Chicago Lawn            53098         3.53 

In [16]:
chi_clean1.shape

(78, 4)

I initially saw on Wikipedia that there were 77 communities but when I ran the .shape function it produced 78 rows. I now realize the 78th row is a total row which is not necessary and will be deleted: 

In [17]:
chi_clean1 = chi_clean1.drop([77])
chi_clean1

Community  2017 Population Area (sq mi)  \
0              Rogers Park            55062         1.84   
1               West Ridge            76215         3.53   
2                   Uptown            57973         2.32   
3           Lincoln Square            41715         2.56   
4             North Center            35789         2.05   
5                Lake View           100470         3.12   
6             Lincoln Park            67710         3.16   
7          Near North Side            88893         2.74   
8              Edison Park            11605         1.13   
9             Norwood Park            37089         4.37   
10          Jefferson Park            26808         2.33   
11             Forest Glen            19019         3.20   
12              North Park            18842         2.52   
13             Albany Park            51992         1.92   
14            Portage Park            64307         3.95   
15             Irving Park            54606         3.21   
16                 Dunning            43689         3.72   
17               Montclare            13830         0.99   
18          Belmont Cragin            79910         3.91   
19                 Hermosa            24144         1.17   
20                Avondale            37368         1.98   
21            Logan Square            73046         3.59   
22           Humboldt Park            56427         3.60   
23               West Town            84502         4.58   
24                  Austin            95260         7.15   
25      West Garfield Park            17163         1.28   
26      East Garfield Park            19996         1.93   
27          Near West Side            62872         5.69   
28          North Lawndale            35947         3.21   
29          South Lawndale            74851         4.59   
30         Lower West Side            32888         2.93   
31          (The) Loop[11]            35880         1.65   
32         Near South Side            23620         1.78   
33           Armour Square            13455         1.00   
34                 Douglas            20781         1.65   
35                 Oakland             6645         0.58   
36             Fuller Park             2439         0.71   
37         Grand Boulevard            22313         1.74   
38                 Kenwood            17189         1.04   
39         Washington Park            11502         1.52   
40               Hyde Park            26827         1.61   
41                Woodlawn            23268         2.07   
42             South Shore            50418         2.93   
43                 Chatham            31120         2.95   
44             Avalon Park             9985         1.25   
45           South Chicago            28263         3.34   
46                Burnside             2254         0.61   
47         Calumet Heights            13188         1.75   
48                Roseland            42433         4.82   
49                 Pullman             6613         2.12   
50           South Deering            14614        10.90   
51               East Side            23737         2.98   
52            West Pullman            27742         3.56   
53               Riverdale             7394         3.53   
54               Hegewisch             9418         5.24   
55          Garfield Ridge            36396         4.23   
56          Archer Heights            13142         2.01   
57           Brighton Park            44813         2.72   
58           McKinley Park            15767         1.41   
59              Bridgeport            33637         2.09   
60                New City            39561         4.83   
61             West Elsdon            19237         1.17   
62               Gage Park            40873         2.20   
63                Clearing            25891         2.55   
64               West Lawn            33108         2.95   
65            Chicago Lawn            53098         3.53 

I've already learned that when I run these Communities through geopy, the results for many communities will be from cities outside Chicago

In [18]:
chi_clean1['Community'] = chi_clean1['Community'].astype(str) + ', Chicago'
chi_clean1

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31          (The) Loop[11], Chicago            35880         1.65   
32         Near South Side, Chicago            23620         1.78   
33           Armour Square, Chicago            13455         1.00   
34                 Douglas, Chicago            20781         1.65   
35                 Oakland, Chicago             6645         0.58   
36             Fuller Park, Chicago             2439         0.71   
37         Grand Boulevard, Chicago            22313         1.74   
38                 Kenwood, Chicago            17189         1.04   
39         Washington Park, Chicago            11502         1.52   
40               Hyde Park, Chicago            26827         1.61   
41                Woodlawn, Chicago            23268         2.07   
42             South Shore, Chicago            50418         2.93   
43                 Chatham, Chicago            31120         2.95   
44             Avalon Park, Chicago             9985         1.25   
45           South Chicago, Chicago            28263         3.34   
46                Burnside, Chicago             2254         0.61   
47         Calumet Heights, Chicago            13188         1.75   
48                Roseland, Chicago            42433         4.82   
49                 Pullman, Chicago             6613         2.12   
50           South Deering, Chicago            14614        10.90   
51               East Side, Chicago            23737         2.98   
52            West Pullman, Chicago            27742         3.56   
53               Riverdale, Chicago             7394         3.53   
54               Hegewisch, Chicago             9418         5.24   
55          Garfield Ridge, Chicago            36396         4.23   
56          Archer Heights, Chicago            13142         2.01   
57           Brighton Pa

### *Now that we have a clean Chicago Community dataframe, in this next section I will pull in latitude & longitude coordinates*

In [19]:
chi_coord = chi_clean1.copy()
chi_coord

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31          (The) Loop[11], Chicago            35880         1.65   
32         Near South Side, Chicago            23620         1.78   
33           Armour Square, Chicago            13455         1.00   
34                 Douglas, Chicago            20781         1.65   
35                 Oakland, Chicago             6645         0.58   
36             Fuller Park, Chicago             2439         0.71   
37         Grand Boulevard, Chicago            22313         1.74   
38                 Kenwood, Chicago            17189         1.04   
39         Washington Park, Chicago            11502         1.52   
40               Hyde Park, Chicago            26827         1.61   
41                Woodlawn, Chicago            23268         2.07   
42             South Shore, Chicago            50418         2.93   
43                 Chatham, Chicago            31120         2.95   
44             Avalon Park, Chicago             9985         1.25   
45           South Chicago, Chicago            28263         3.34   
46                Burnside, Chicago             2254         0.61   
47         Calumet Heights, Chicago            13188         1.75   
48                Roseland, Chicago            42433         4.82   
49                 Pullman, Chicago             6613         2.12   
50           South Deering, Chicago            14614        10.90   
51               East Side, Chicago            23737         2.98   
52            West Pullman, Chicago            27742         3.56   
53               Riverdale, Chicago             7394         3.53   
54               Hegewisch, Chicago             9418         5.24   
55          Garfield Ridge, Chicago            36396         4.23   
56          Archer Heights, Chicago            13142         2.01   
57           Brighton Pa

In [20]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="foursquare_agent")
from geopy.extra.rate_limiter import RateLimiter
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
chi_coord['location'] = chi_coord['Community'].apply(geocode)
chi_coord['point'] = chi_coord['location'].apply(lambda loc: tuple(loc.point) if loc else None)
chi_coord

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31          (The) Loop[11], Chicago            35880         1.65   
32         Near South Side, Chicago            23620         1.78   
33           Armour Square, Chicago            13455         1.00   
34                 Douglas, Chicago            20781         1.65   
35                 Oakland, Chicago             6645         0.58   
36             Fuller Park, Chicago             2439         0.71   
37         Grand Boulevard, Chicago            22313         1.74   
38                 Kenwood, Chicago            17189         1.04   
39         Washington Park, Chicago            11502         1.52   
40               Hyde Park, Chicago            26827         1.61   
41                Woodlawn, Chicago            23268         2.07   
42             South Shore, Chicago            50418         2.93   
43                 Chatham, Chicago            31120         2.95   
44             Avalon Park, Chicago             9985         1.25   
45           South Chicago, Chicago            28263         3.34   
46                Burnside, Chicago             2254         0.61   
47         Calumet Heights, Chicago            13188         1.75   
48                Roseland, Chicago            42433         4.82   
49                 Pullman, Chicago             6613         2.12   
50           South Deering, Chicago            14614        10.90   
51               East Side, Chicago            23737         2.98   
52            West Pullman, Chicago            27742         3.56   
53               Riverdale, Chicago             7394         3.53   
54               Hegewisch, Chicago             9418         5.24   
55          Garfield Ridge, Chicago            36396         4.23   
56          Archer Heights, Chicago            13142         2.01   
57           Brighton Pa

In [21]:
#Let's create a copy at this point since every time I want to go back and make changes it takes 3 minutes to run the geopy

chi_coord1 = chi_coord.copy()
chi_coord1


Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31          (The) Loop[11], Chicago            35880         1.65   
32         Near South Side, Chicago            23620         1.78   
33           Armour Square, Chicago            13455         1.00   
34                 Douglas, Chicago            20781         1.65   
35                 Oakland, Chicago             6645         0.58   
36             Fuller Park, Chicago             2439         0.71   
37         Grand Boulevard, Chicago            22313         1.74   
38                 Kenwood, Chicago            17189         1.04   
39         Washington Park, Chicago            11502         1.52   
40               Hyde Park, Chicago            26827         1.61   
41                Woodlawn, Chicago            23268         2.07   
42             South Shore, Chicago            50418         2.93   
43                 Chatham, Chicago            31120         2.95   
44             Avalon Park, Chicago             9985         1.25   
45           South Chicago, Chicago            28263         3.34   
46                Burnside, Chicago             2254         0.61   
47         Calumet Heights, Chicago            13188         1.75   
48                Roseland, Chicago            42433         4.82   
49                 Pullman, Chicago             6613         2.12   
50           South Deering, Chicago            14614        10.90   
51               East Side, Chicago            23737         2.98   
52            West Pullman, Chicago            27742         3.56   
53               Riverdale, Chicago             7394         3.53   
54               Hegewisch, Chicago             9418         5.24   
55          Garfield Ridge, Chicago            36396         4.23   
56          Archer Heights, Chicago            13142         2.01   
57           Brighton Pa

In [22]:
#Let's remove row#31 "(The)Loop[11], Chicago" since it did not produce coordinates
chi_coord1 = chi_coord1.drop([31])
chi_coord1


Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
32         Near South Side, Chicago            23620         1.78   
33           Armour Square, Chicago            13455         1.00   
34                 Douglas, Chicago            20781         1.65   
35                 Oakland, Chicago             6645         0.58   
36             Fuller Park, Chicago             2439         0.71   
37         Grand Boulevard, Chicago            22313         1.74   
38                 Kenwood, Chicago            17189         1.04   
39         Washington Park, Chicago            11502         1.52   
40               Hyde Park, Chicago            26827         1.61   
41                Woodlawn, Chicago            23268         2.07   
42             South Shore, Chicago            50418         2.93   
43                 Chatham, Chicago            31120         2.95   
44             Avalon Park, Chicago             9985         1.25   
45           South Chicago, Chicago            28263         3.34   
46                Burnside, Chicago             2254         0.61   
47         Calumet Heights, Chicago            13188         1.75   
48                Roseland, Chicago            42433         4.82   
49                 Pullman, Chicago             6613         2.12   
50           South Deering, Chicago            14614        10.90   
51               East Side, Chicago            23737         2.98   
52            West Pullman, Chicago            27742         3.56   
53               Riverdale, Chicago             7394         3.53   
54               Hegewisch, Chicago             9418         5.24   
55          Garfield Ridge, Chicago            36396         4.23   
56          Archer Heights, Chicago            13142         2.01   
57           Brighton Park, Chicago            44813         2.72   
58           McKinley Pa

In [23]:
#Now let's reindex since the indexing column is skipping the #31 we just removed:

chi_coord1 = chi_coord1.reset_index()
chi_coord1

index                        Community  2017 Population Area (sq mi)  \
0       0             Rogers Park, Chicago            55062         1.84   
1       1              West Ridge, Chicago            76215         3.53   
2       2                  Uptown, Chicago            57973         2.32   
3       3          Lincoln Square, Chicago            41715         2.56   
4       4            North Center, Chicago            35789         2.05   
5       5               Lake View, Chicago           100470         3.12   
6       6            Lincoln Park, Chicago            67710         3.16   
7       7         Near North Side, Chicago            88893         2.74   
8       8             Edison Park, Chicago            11605         1.13   
9       9            Norwood Park, Chicago            37089         4.37   
10     10          Jefferson Park, Chicago            26808         2.33   
11     11             Forest Glen, Chicago            19019         3.20   
12     12              North Park, Chicago            18842         2.52   
13     13             Albany Park, Chicago            51992         1.92   
14     14            Portage Park, Chicago            64307         3.95   
15     15             Irving Park, Chicago            54606         3.21   
16     16                 Dunning, Chicago            43689         3.72   
17     17               Montclare, Chicago            13830         0.99   
18     18          Belmont Cragin, Chicago            79910         3.91   
19     19                 Hermosa, Chicago            24144         1.17   
20     20                Avondale, Chicago            37368         1.98   
21     21            Logan Square, Chicago            73046         3.59   
22     22           Humboldt Park, Chicago            56427         3.60   
23     23               West Town, Chicago            84502         4.58   
24     24                  Austin, Chicago            95260         7.15   
25     25      West Garfield Park, Chicago            17163         1.28   
26     26      East Garfield Park, Chicago            19996         1.93   
27     27          Near West Side, Chicago            62872         5.69   
28     28          North Lawndale, Chicago            35947         3.21   
29     29          South Lawndale, Chicago            74851         4.59   
30     30         Lower West Side, Chicago            32888         2.93   
31     32         Near South Side, Chicago            23620         1.78   
32     33           Armour Square, Chicago            13455         1.00   
33     34                 Douglas, Chicago            20781         1.65   
34     35                 Oakland, Chicago             6645         0.58   
35     36             Fuller Park, Chicago             2439         0.71   
36     37         Grand Boulevard, Chicago            22313         1.74   
37     38                 Kenwood, Chicago            17189         1.04   
38     39         Washington Park, Chicago            11502         1.52   
39     40               Hyde Park, Chicago            26827         1.61   
40     41                Woodlawn, Chicago            23268         2.07   
41     42             South Shore, Chicago            50418         2.93   
42     43                 Chatham, Chicago            31120         2.95   
43     44             Avalon Park, Chicago             9985         1.25   
44     45           South Chicago, Chicago            28263         3.34   
45     46                Burnside, Chicago             2254         0.61   
46     47         Calumet Heights, Chicago            13188         1.75   
47     48                Roseland, Chicago            42433         4.82   
48     49                 Pullman, Chicago             6613         2.12   
49     50           South Deering, Chicago            14614        10.90   
50     51               East Side, Chicago            23737         2.98   
51     52            West Pullman, Chicago          

In [24]:
#And now this produces an additional index column, so we must remove the old index column missing #31:

chi_coord1 = chi_coord1.drop('index', 1)

chi_coord1

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

I spent 10+ hours trying to learn how to get geopy / Nominatim to add these location and point columns and I could not figure out how to just extract latitude & longitude from geopy so I decided to just extract the values directly from the df:

In [25]:
chi_coord1[['Latitude', 'Longitude', 'Height']] = pd.DataFrame(chi_coord1.point.tolist(), index=chi_coord1.index)
chi_coord1

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

Now that I have latitude & longitude in their own columns, I'll remove the other columns no longer needed:

In [26]:
chi_clean2 = chi_coord1.drop ('location', 1)
chi_clean2

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

In [27]:
chi_clean3 = chi_clean2.drop ('point', 1)
chi_clean3

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

In [28]:
chi_clean4 = chi_clean3.drop ('Height', 1)
chi_clean4

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

*I had trouble using the same df name to drop columns repeatedly without old columns popping back up so I decided to speed things up and just use new names as I dropped each additional column. I also recognize that some coordinates are not in Chicago and I was not able to figure out how to pull these communities specific to Chicago using Geopy so I will now manuall remove the following: Uptown New Orleans, Lincoln Square NY

Let's see what this data looks like on a map of Chicago:

In [29]:
#Define our map area and define location, latitide & longitude for geopy to run
address = 'Chicago, IL'

geolocator = Nominatim(user_agent="ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Chicago, IL are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Chicago, IL are 41.8755616, -87.6244212.


In [30]:
# create map of Chicago using latitude and longitude values
map_chicago = folium.Map(location=[latitude, longitude], zoom_start=10)


# add markers to map
for lat, lng, community, in zip(chi_clean4['Latitude'], chi_clean4['Longitude'], chi_clean4['Community']):
    label = '{}'.format(community)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_chicago)  
    
map_chicago

### Now that we have a solid dataframe of the communities in Chicago and their coordinates placed on the map, I will gather venue information for each community

#### Define Foursquare Credentials and Version

In [31]:
CLIENT_ID = 'MLTOHZTUFRKGHKUQR4O2PMTX3ANCOZ3XMLSUC2VNFJMISJ4X' # your Foursquare ID
CLIENT_SECRET = 'STFZYX1G3PNUCPAZFLQM14IJAGZKRHCSJILKK35JNWZZQFW3' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: MLTOHZTUFRKGHKUQR4O2PMTX3ANCOZ3XMLSUC2VNFJMISJ4X
CLIENT_SECRET:STFZYX1G3PNUCPAZFLQM14IJAGZKRHCSJILKK35JNWZZQFW3


#### Let's explore the first neighborhood in our dataframe.

In [32]:
# Get the neighborhood's name.
chi_clean4.loc[0, 'Community']

'Rogers Park, Chicago'

In [33]:
# Get the neighborhood's latitude and longitude values.
community_latitude = chi_clean4.loc[0, 'Latitude'] # neighborhood latitude value
community_longitude = chi_clean4.loc[0, 'Longitude'] # neighborhood longitude value

community_name = chi_clean4.loc[0, 'Community'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(community_name, 
                                                               community_latitude, 
                                                               community_longitude))

Latitude and longitude values of Rogers Park, Chicago are 42.01053135, -87.67074819664808.


#### Now, let's get the top 100 venues that are in Rogers Park within a radius of 500 meters.

First, let's create the GET request URL. Name your URL **url**.

In [34]:
LIMIT = 100

radius = 500

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    community_latitude, 
    community_longitude, 
    radius, 
    LIMIT)
url

'https://api.foursquare.com/v2/venues/explore?&client_id=MLTOHZTUFRKGHKUQR4O2PMTX3ANCOZ3XMLSUC2VNFJMISJ4X&client_secret=STFZYX1G3PNUCPAZFLQM14IJAGZKRHCSJILKK35JNWZZQFW3&v=20180605&ll=42.01053135,-87.67074819664808&radius=500&limit=100'

Send the GET request and examine the results

In [35]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5ee11a72dc59643ef4c98f20'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': '$-$$$$', 'key': 'price'},
    {'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Rogers Park',
  'headerFullLocation': 'Rogers Park, Chicago',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 33,
  'suggestedBounds': {'ne': {'lat': 42.0150313545, 'lng': -87.66470314878757},
   'sw': {'lat': 42.0060313455, 'lng': -87.67679324450859}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4b6ed827f964a5200bcd2ce3',
       'name': 'El Famous Burrito',
       'location': {'address': '7047 N Clark St',
        'crossStreet': 'Greenleaf',
        'lat': 42.01042128720865,
        'lng': -87.67420436237607,


From previous exercises we know that all the information is in the *items* key. Before we proceed, let's borrow the **get_category_type** function from the Foursquare lab.

In [36]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

Now we are ready to clean the json and structure it into a *pandas* dataframe.

In [37]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.head(10)

name          categories        lat        lng
0                  El Famous Burrito  Mexican Restaurant  42.010421 -87.674204
1  Taqueria & Restaurant Cd. Hidalgo  Mexican Restaurant  42.011634 -87.674484
2                 Morse Fresh Market       Grocery Store  42.008087 -87.667041
3                     The Common Cup         Coffee Shop  42.007797 -87.667901
4                          Smack Dab              Bakery  42.009291 -87.666201
5                         Bark Place           Pet Store  42.010080 -87.675223
6             Glenwood Sunday Market      Farmers Market  42.008525 -87.666251
7        Romanian Kosher Sausage Co.       Deli / Bodega  42.012765 -87.674692
8                       The Glenwood                 Bar  42.008502 -87.666273
9                       China Spring  Chinese Restaurant  42.009111 -87.673965

In [38]:
#Let's check to see how many hits we received to verify if the limit of 100 was hit with only a 500 radius:

nearby_venues.shape

(33, 4)

With only 33 venues, I don't feel we have a large enough pool to correctly learn how many coffee shops will be nearby and if there are any donut shops nearby for all communities. At this point I will expand the radius to find more venues

In [39]:
LIMIT = 100

radius = 1000

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    community_latitude, 
    community_longitude, 
    radius, 
    LIMIT)
url

'https://api.foursquare.com/v2/venues/explore?&client_id=MLTOHZTUFRKGHKUQR4O2PMTX3ANCOZ3XMLSUC2VNFJMISJ4X&client_secret=STFZYX1G3PNUCPAZFLQM14IJAGZKRHCSJILKK35JNWZZQFW3&v=20180605&ll=42.01053135,-87.67074819664808&radius=1000&limit=100'

In [40]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5ee11cf3057b150fc02dbab5'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': 'Open now', 'key': 'openNow'},
    {'name': '$-$$$$', 'key': 'price'}]},
  'headerLocation': 'Rogers Park',
  'headerFullLocation': 'Rogers Park, Chicago',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 123,
  'suggestedBounds': {'ne': {'lat': 42.01953135900001,
    'lng': -87.65865810092707},
   'sw': {'lat': 42.00153134099999, 'lng': -87.68283829236908}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ad3bfc1f964a52017e620e3',
       'name': 'Morse Fresh Market',
       'location': {'address': '1430 W Morse Ave',
        'crossStreet': 'at Greenview Ave',
        'lat': 42.008086562847986,
        'lng

In [41]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [42]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.shape

(100, 4)

Ok, I reran the prcess with radius of 750 and received 80 venues, but I want to stretch to 100 in case some communities are smaller and produce less results. I ran again using radius = 1,000 and now that produced 100 venues which is out limit, so I will leave it at that.

### We are making great progress now. The next step is to create a function to repeat the same process for all the Chicago communities in our list

In [43]:
def getNearbyVenues(names, latitudes, longitudes, radius=750):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url)
        print(results)
        results = results.json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Community', 
                  'Community Latitude', 
                  'Community Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

#### Now write the code to run the above function on each neighborhood and create a new dataframe called *chicago_venues*.

In [44]:
chicago_venues = getNearbyVenues(names=chi_clean4['Community'],
                                   latitudes=chi_clean4['Latitude'],
                                   longitudes=chi_clean4['Longitude']
                                  )

Rogers Park, Chicago
<Response [200]>
West Ridge, Chicago
<Response [200]>
Uptown, Chicago
<Response [200]>
Lincoln Square, Chicago
<Response [200]>
North Center, Chicago
<Response [200]>
Lake View, Chicago
<Response [200]>
Lincoln Park, Chicago
<Response [200]>
Near North Side, Chicago
<Response [200]>
Edison Park, Chicago
<Response [200]>
Norwood Park, Chicago
<Response [200]>
Jefferson Park, Chicago
<Response [200]>
Forest Glen, Chicago
<Response [200]>
North Park, Chicago
<Response [200]>
Albany Park, Chicago
<Response [200]>
Portage Park, Chicago
<Response [200]>
Irving Park, Chicago
<Response [200]>
Dunning, Chicago
<Response [200]>
Montclare, Chicago
<Response [200]>
Belmont Cragin, Chicago
<Response [200]>
Hermosa, Chicago
<Response [200]>
Avondale, Chicago
<Response [200]>
Logan Square, Chicago
<Response [200]>
Humboldt Park, Chicago
<Response [200]>
West Town, Chicago
<Response [200]>
Austin, Chicago
<Response [200]>
West Garfield Park, Chicago
<Response [200]>
East Garfield 

Ok, so after deciding to use 1,000 as the radius, it turns out the Foursquare API crashed over and over and over and over, dozens of times. I decided to go to 500 to see if that was the issue and 500 radius worked the first time, but it only produced an average of 17 venues per community. I bumped the radius up to 750 and it crashed a few times but made it mostly through the list each time so I kept at it and it eventually made it all the way without crashing. This produced an average of 34 venues per community, so this is what I will go with. 

#### Let's check the size of the resulting dataframe

In [45]:
print(chicago_venues.shape)
chicago_venues.head()

(2580, 7)


Community  Community Latitude  Community Longitude  \
0  Rogers Park, Chicago           42.010531           -87.670748   
1  Rogers Park, Chicago           42.010531           -87.670748   
2  Rogers Park, Chicago           42.010531           -87.670748   
3  Rogers Park, Chicago           42.010531           -87.670748   
4  Rogers Park, Chicago           42.010531           -87.670748   

                               Venue  Venue Latitude  Venue Longitude  \
0                  El Famous Burrito       42.010421       -87.674204   
1  Taqueria & Restaurant Cd. Hidalgo       42.011634       -87.674484   
2                 Morse Fresh Market       42.008087       -87.667041   
3                     The Common Cup       42.007797       -87.667901   
4                          Smack Dab       42.009291       -87.666201   

       Venue Category  
0  Mexican Restaurant  
1  Mexican Restaurant  
2       Grocery Store  
3         Coffee Shop  
4              Bakery

Let's check how many venues were returned for each neighborhood

In [46]:
chicago_venues.groupby('Community').count()

Community Latitude  Community Longitude  \
Community                                                                  
Albany Park, Chicago                             46                   46   
Archer Heights, Chicago                          31                   31   
Armour Square, Chicago                           28                   28   
Ashburn, Chicago                                 15                   15   
Auburn Gresham, Chicago                           9                    9   
Austin, Chicago                                   4                    4   
Avalon Park, Chicago                             10                   10   
Avondale, Chicago                                71                   71   
Belmont Cragin, Chicago                          33                   33   
Beverly, Chicago                                 21                   21   
Bridgeport, Chicago                              60                   60   
Brighton Park, Chicago                           20                   20   
Burnside, Chicago                                 7                    7   
Calumet Heights, Chicago                         14                   14   
Chatham, Chicago                                 33                   33   
Chicago Lawn, Chicago                            36                   36   
Clearing, Chicago                                20                   20   
Douglas, Chicago                                 39                   39   
Dunning, Chicago                                 22                   22   
East Garfield Park, Chicago                      22                   22   
East Side, Chicago                               16                   16   
Edgewater, Chicago                              100                  100   
Edison Park, Chicago                             27                   27   
Englewood, Chicago                               16                   16   
Forest Glen, Chicago                             12                   12   
Fuller Park, Chicago                             10                   10   
Gage Park, Chicago                               19                   19   
Garfield Ridge, Chicago                          22                   22   
Grand Boulevard, Chicago                         30                   30   
Greater Grand Crossing, Chicago                  15                   15   
Hegewisch, Chicago                               14                   14   
Hermosa, Chicago                                 33                   33   
Humboldt Park, Chicago                           34                   34   
Hyde Park, Chicago                              100                  100   
Irving Park, Chicago                             35                   35   
Jefferson Park, Chicago                          44                   44   
Kenwood, Chicago                                 28                   28   
Lake View, Chicago                              100                  100   
Lincoln Park, Chicago                            61                   61   
Lincoln Square, Chicago                          41                   41   
Logan Square, Chicago                           100                  100   
Lower West Side, Chicago                         30                   30   
McKinley Park, Chicago                           34                   34   
Montclare, Chicago                               30                   30   
Morgan Park, Chicago                             11                   11   
Mount Greenwood, Chicago                          6                    6   
Near North Side, Chicago                        100                  100   
Near South Side, Chicago                         92                   92   
Near West Side, Chicago                          67                   67   
New City, Chicago                                17                   17   
North Center, Chicago                           100                  100   
North

I was originally disheartened with the Foursquare API crashing over and over and limiting the average venue to 30-some per community, but now that I see the list I realize some communities are quite small and are not going to be our target anyway, and there are at least a doxen or two with close to 100 venues so I am confident we will still have a decent sample size.

#### Let's find out how many unique categories can be curated from all the returned venues

In [47]:
print('There are {} uniques categories.'.format(len(chicago_venues['Venue Category'].unique())))

There are 302 uniques categories.


### The next major step is to analyze each community

In [48]:
# one hot encoding
chicago_onehot = pd.get_dummies(chicago_venues[['Venue Category']], prefix="", prefix_sep="")

# add community column back to dataframe
chicago_onehot['Community'] = chicago_venues['Community'] 

# move community column to the first column
fixed_columns = [chicago_onehot.columns[-1]] + list(chicago_onehot.columns[:-1])
chicago_onehot = chicago_onehot[fixed_columns]

chicago_onehot.head()

Community  ATM  Accessories Store  African Restaurant  Airport  \
0  Rogers Park, Chicago    0                  0                   0        0   
1  Rogers Park, Chicago    0                  0                   0        0   
2  Rogers Park, Chicago    0                  0                   0        0   
3  Rogers Park, Chicago    0                  0                   0        0   
4  Rogers Park, Chicago    0                  0                   0        0   

   Airport Lounge  Airport Service  American Restaurant  Antique Shop  Arcade  \
0               0                0                    0             0       0   
1               0                0                    0             0       0   
2               0                0                    0             0       0   
3               0                0                    0             0       0   
4               0                0                    0             0       0   

   Argentinian Restaurant  Art Gallery  Art Museum  Arts & Crafts Store  \
0                       0            0           0                    0   
1                       0            0           0                    0   
2                       0            0           0                    0   
3                       0            0           0                    0   
4                       0            0           0                    0   

   Asian Restaurant  Athletics & Sports  Auditorium  Auto Dealership  \
0                 0                   0           0                0   
1                 0                   0           0                0   
2                 0                   0           0                0   
3                 0                   0           0                0   
4                 0                   0           0                0   

   Automotive Shop  BBQ Joint  Bagel Shop  Bakery  Bank  Bar  Baseball Field  \
0                0          0           0       0     0    0               0   
1                0          0           0       0     0    0               0   
2                0          0           0       0     0    0               0   
3                0          0           0       0     0    0               0   
4                0          0           0       1     0    0               0   

   Baseball Stadium  Basketball Court  Basketball Stadium  Beach  \
0                 0                 0                   0      0   
1                 0                 0                   0      0   
2                 0                 0                   0      0   
3                 0                 0                   0      0   
4                 0                 0                   0      0   

   Bed & Breakfast  Beer Bar  Beer Garden  Beer Store  Big Box Store  \
0                0         0            0           0              0   
1                0         0            0           0              0   
2                0         0            0           0              0   
3                0         0            0           0              0   
4                0         0            0           0              0   

   Bike Rental / Bike Share  Bike Shop  Bike Trail  Bistro  Board Shop  \
0                         0          0           0       0           0   
1                         0          0           0       0           0   
2                         0          0           0       0           0   
3                         0          0           0       0           0   
4                         0          0           0       0           0   

   Boat or Ferry  Bookstore  Border Crossing  Boutique  Bowling Alley  \
0              0          0                0         0              0   
1              0          0                0         0              0   
2              0          0                0         0              0   
3              0          0                0         0              0   
4              0          0  

And let's examine the new dataframe size.

In [49]:
chicago_onehot.shape

(2580, 303)

#### Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [50]:
chicago_grouped = chicago_onehot.groupby('Community').mean().reset_index()
chicago_grouped

Community       ATM  Accessories Store  \
0              Albany Park, Chicago  0.000000           0.000000   
1           Archer Heights, Chicago  0.000000           0.000000   
2            Armour Square, Chicago  0.000000           0.000000   
3                  Ashburn, Chicago  0.000000           0.000000   
4           Auburn Gresham, Chicago  0.000000           0.000000   
5                   Austin, Chicago  0.000000           0.000000   
6              Avalon Park, Chicago  0.000000           0.000000   
7                 Avondale, Chicago  0.014085           0.000000   
8           Belmont Cragin, Chicago  0.000000           0.000000   
9                  Beverly, Chicago  0.000000           0.000000   
10              Bridgeport, Chicago  0.000000           0.000000   
11           Brighton Park, Chicago  0.000000           0.000000   
12                Burnside, Chicago  0.000000           0.000000   
13         Calumet Heights, Chicago  0.000000           0.000000   
14                 Chatham, Chicago  0.000000           0.000000   
15            Chicago Lawn, Chicago  0.000000           0.000000   
16                Clearing, Chicago  0.000000           0.000000   
17                 Douglas, Chicago  0.000000           0.000000   
18                 Dunning, Chicago  0.000000           0.000000   
19      East Garfield Park, Chicago  0.000000           0.000000   
20               East Side, Chicago  0.062500           0.000000   
21               Edgewater, Chicago  0.000000           0.000000   
22             Edison Park, Chicago  0.000000           0.000000   
23               Englewood, Chicago  0.062500           0.000000   
24             Forest Glen, Chicago  0.000000           0.000000   
25             Fuller Park, Chicago  0.000000           0.000000   
26               Gage Park, Chicago  0.000000           0.000000   
27          Garfield Ridge, Chicago  0.000000           0.000000   
28         Grand Boulevard, Chicago  0.000000           0.000000   
29  Greater Grand Crossing, Chicago  0.000000           0.000000   
30               Hegewisch, Chicago  0.000000           0.000000   
31                 Hermosa, Chicago  0.000000           0.000000   
32           Humboldt Park, Chicago  0.000000           0.000000   
33               Hyde Park, Chicago  0.000000           0.000000   
34             Irving Park, Chicago  0.000000           0.000000   
35          Jefferson Park, Chicago  0.000000           0.000000   
36                 Kenwood, Chicago  0.000000           0.000000   
37               Lake View, Chicago  0.000000           0.000000   
38            Lincoln Park, Chicago  0.000000           0.000000   
39          Lincoln Square, Chicago  0.000000           0.000000   
40            Logan Square, Chicago  0.000000           0.000000   
41         Lower West Side, Chicago  0.000000           0.000000   
42           McKinley Park, Chicago  0.000000           0.000000   
43               Montclare, Chicago  0.000000           0.000000   
44             Morgan Park, Chicago  0.000000           0.000000   
45         Mount Greenwood, Chicago  0.000000           0.000000   
46         Near North Side, Chicago  0.000000           0.000000   
47         Near South Side, Chicago  0.000000           0.000000   
48          Near West Side, Chicago  0.000000           0.000000   
49                New City, Chicago  0.000000           0.000000   
50            North Center, Chicago  0.000000           0.000000   
51          North Lawndale, Chicago  0.000000           0.000000   
52              North Park, Chicago  0.000000           0.000000   
53            Norwood Park, Chicago  0.000000           0.000000   
54                  O'Hare, Chicago  0.000000           0.047059   
55                 Oakland, Chicago  0.000000           0.000000   
56            Portage Park, Chicago  0.000000           0.000000   
57                 Pullman, Chicago  0.000000           0.000000   
58            

#### Let's confirm the new size

In [51]:
chicago_grouped.shape

(76, 303)

#### Let's print each neighborhood along with the top 5 most common venues

In [52]:
num_top_venues = 5

for hood in chicago_grouped['Community']:
    print("----"+hood+"----")
    temp = chicago_grouped[chicago_grouped['Community'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Albany Park, Chicago----
                venue  freq
0    Asian Restaurant  0.07
1  Mexican Restaurant  0.07
2  Chinese Restaurant  0.04
3   Korean Restaurant  0.04
4      Sandwich Place  0.04


----Archer Heights, Chicago----
                venue  freq
0  Mexican Restaurant  0.13
1      Clothing Store  0.06
2      Cosmetics Shop  0.06
3       Grocery Store  0.06
4   Mobile Phone Shop  0.06


----Armour Square, Chicago----
                venue  freq
0  Chinese Restaurant  0.14
1         Bus Station  0.07
2                 Bar  0.07
3         Pizza Place  0.07
4  Mexican Restaurant  0.04


----Ashburn, Chicago----
                venue  freq
0                Park  0.13
1       Train Station  0.13
2        Liquor Store  0.13
3      Clothing Store  0.07
4  Light Rail Station  0.07


----Auburn Gresham, Chicago----
                  venue  freq
0              Boutique  0.11
1        Discount Store  0.11
2      Basketball Court  0.11
3                Lounge  0.11
4  Fast Food Restaura

                venue  freq
0         Coffee Shop  0.09
1          Donut Shop  0.09
2  Mexican Restaurant  0.06
3         Video Store  0.06
4               Diner  0.06


----Montclare, Chicago----
                  venue  freq
0  Fast Food Restaurant  0.10
1    Mexican Restaurant  0.07
2         Train Station  0.07
3     Martial Arts Dojo  0.07
4           Pizza Place  0.07


----Morgan Park, Chicago----
                 venue  freq
0            BBQ Joint  0.27
1        Train Station  0.09
2  American Restaurant  0.09
3               Lounge  0.09
4                 Park  0.09


----Mount Greenwood, Chicago----
           venue  freq
0           Park  0.33
1   Home Service  0.17
2  Women's Store  0.17
3            Gym  0.17
4      Gift Shop  0.17


----Near North Side, Chicago----
         venue  freq
0  Coffee Shop  0.07
1        Hotel  0.06
2   Steakhouse  0.06
3          Gym  0.05
4          Bar  0.04


----Near South Side, Chicago----
                venue  freq
0                Park

#### Let's put that into a *pandas* dataframe

First, let's write a function to sort the venues in descending order.

In [53]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

Now let's create the new dataframe and display the top 10 venues for each neighborhood.

In [54]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Community']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
communities_venues_sorted = pd.DataFrame(columns=columns)
communities_venues_sorted['Community'] = chicago_grouped['Community']

for ind in np.arange(chicago_grouped.shape[0]):
    communities_venues_sorted.iloc[ind, 1:] = return_most_common_venues(chicago_grouped.iloc[ind, :], num_top_venues)

communities_venues_sorted.head()

Community 1st Most Common Venue 2nd Most Common Venue  \
0     Albany Park, Chicago    Mexican Restaurant      Asian Restaurant   
1  Archer Heights, Chicago    Mexican Restaurant        Clothing Store   
2   Armour Square, Chicago    Chinese Restaurant           Pizza Place   
3         Ashburn, Chicago         Train Station                  Park   
4  Auburn Gresham, Chicago         Grocery Store        Discount Store   

             3rd Most Common Venue 4th Most Common Venue  \
0                       Donut Shop                  Park   
1                   Cosmetics Shop     Mobile Phone Shop   
2                              Bar           Bus Station   
3                     Liquor Store        Cosmetics Shop   
4  Southern / Soul Food Restaurant  Fast Food Restaurant   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0         Grocery Store                Bakery     Korean Restaurant   
1         Grocery Store   Arts & Crafts Store         Big Box Store   
2      Asian Restaurant        Sandwich Place    Seafood Restaurant   
3    Mexican Restaurant             Locksmith       Automotive Shop   
4      Basketball Court                Lounge                  Park   

  8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0           Coffee Shop        Sandwich Place     Chinese Restaurant  
1             Nightclub    Seafood Restaurant                    Bar  
2      Storage Facility                Bakery             Bagel Shop  
3        Clothing Store    Light Rail Station            Pizza Place  
4              Boutique   American Restaurant       Department Store

### In this next step, we will cluster the neighborhoods together. I recognize micro analyzing each small community may produce too small of a set of venues for making such an important decision. Clustering will allow us to aggregate the communities closest to one another which still dividing Chicago into small areas

Run *k*-means to cluster the neighborhood into 5 clusters.

In [55]:
# set number of clusters
kclusters = 5

chicago_grouped_clustering = chicago_grouped.drop('Community', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(chicago_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([0, 0, 0, 0, 0, 2, 0, 0, 0, 0], dtype=int32)

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

In [56]:
# add clustering labels
communities_venues_sorted.insert(0, 'Cluster Labels New2', kmeans.labels_)

chicago_merged = chi_clean4

# merge chicago_grouped with chicago_data to add latitude/longitude for each community
chicago_merged = chicago_merged.join(communities_venues_sorted.set_index('Community'), on='Community')

chicago_merged.head() # check the last columns!

Community  2017 Population Area (sq mi)  \
0     Rogers Park, Chicago            55062         1.84   
1      West Ridge, Chicago            76215         3.53   
2          Uptown, Chicago            57973         2.32   
3  Lincoln Square, Chicago            41715         2.56   
4    North Center, Chicago            35789         2.05   

   2017 Population Density (/sq mi)   Latitude  Longitude  \
0                          29925.00  42.010531 -87.670748   
1                          21590.65  42.003548 -87.696243   
2                          24988.36  41.966630 -87.655546   
3                          16294.92  41.975990 -87.689616   
4                          17458.05  41.956107 -87.679160   

   Cluster Labels New2 1st Most Common Venue  2nd Most Common Venue  \
0                    0    Mexican Restaurant                   Park   
1                    0     Indian Restaurant   Pakistani Restaurant   
2                    0           Coffee Shop  Vietnamese Restaurant   
3                    0                   Bar            Karaoke Bar   
4                    0                   Bar            Coffee Shop   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0        Sandwich Place           Pizza Place                   Bar   
1         Grocery Store                  Park       Automotive Shop   
2           Pizza Place    Chinese Restaurant                 Diner   
3     Korean Restaurant            Food Truck                Bakery   
4    Mexican Restaurant                   Pub    Chinese Restaurant   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0                Bakery   American Restaurant               Theater   
1     Convenience Store        Clothing Store        Sandwich Place   
2                   Bar       Thai Restaurant         Grocery Store   
3       Thai Restaurant           Bus Station             Juice Bar   
4               Brewery           Pizza Place   American Restaurant   

  9th Most Common Venue 10th Most Common Venue  
0    Chinese Restaurant          Train Station  
1      Business Service   Fast Food Restaurant  
2      Sushi Restaurant     Mexican Restaurant  
3   Rental Car Location       Sushi Restaurant  
4          Dessert Shop                   Bank

Finally, let's visualize the resulting clusters

In [57]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, community, cluster in zip(chicago_merged['Latitude'], chicago_merged['Longitude'], chicago_merged['Community'], chicago_merged['Cluster Labels New2']):
    label = folium.Popup(str(community) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

### Examine Clusters


Now, we can examine each cluster and determine the discriminating venue categories that distinguish each cluster.

In [58]:
chicago_merged.loc[chicago_merged['Cluster Labels New2'] == 0, chicago_merged.columns[[1] + list(range(5, chicago_merged.shape[1]))]]

2017 Population  Longitude  Cluster Labels New2  \
0             55062 -87.670748                    0   
1             76215 -87.696243                    0   
2             57973 -87.655546                    0   
3             41715 -87.689616                    0   
4             35789 -87.679160                    0   
5            100470 -87.655429                    0   
6             67710 -87.638117                    0   
7             88893 -87.634497                    0   
8             11605 -87.814016                    0   
9             37089 -87.800582                    0   
10            26808 -87.763118                    0   
11            19019 -87.751674                    0   
12            18842 -87.722933                    0   
13            51992 -87.716174                    0   
14            64307 -87.765059                    0   
15            54606 -87.736447                    0   
16            43689 -87.796449                    0   
17            13830 -87.798457                    0   
18            79910 -87.768670                    0   
19            24144 -87.734502                    0   
20            37368 -87.711168                    0   
21            73046 -87.706793                    0   
22            56427 -87.704174                    0   
23            84502 -87.686166                    0   
25            17163 -87.729223                    0   
26            19996 -87.702833                    0   
27            62872 -87.666762                    0   
28            35947 -87.713881                    0   
29            74851 -87.713273                    0   
30            32888 -87.671774                    0   
31            23620 -87.624774                    0   
32            13455 -87.633107                    0   
33            20781 -87.617954                    0   
34             6645 -87.608242                    0   
35             2439 -87.632551                    0   
36            22313 -87.617272                    0   
37            17189 -87.597991                    0   
38            11502 -87.618105                    0   
39            26827 -87.592562                    0   
40            23268 -87.599493                    0   
41            50418 -87.575283                    0   
42            31120 -87.612548                    0   
43             9985 -87.588658                    0   
44            28263 -87.551322                    0   
46            13188 -87.579213                    0   
47            42433 -87.625881                    0   
50            23737 -87.534827                    0   
53             9418 -87.546988                    0   
54            36396 -87.745489                    0   
55            13142 -87.726165                    0   
56            44813 -87.698942                    0   
57            15767 -87.673664                    0   
58            33637 -87.651028                    0   
59            39561 -87.656440                    0   
60            19237 -87.724498                    0   
61            40873 -87.696164                    0   
62            25891 -87.773388                    0   
63            33108 -87.722275                    0   
64            53098 -87.696441                    0   
65            29929 -87.666718                    0   
66            25075 -87.645884                    0   
67            31766 -87.620845                    0   
68            43792 -87.711163                    0   
69            46278 -87.656042                    0   
70            20822 -87.671767                    0   
71            27453 -87.656160                    0   
72            19277 -87.708662                    0   
73            22394 -87.666716                    0   
74            12377 -87.906768                    0   
75            55965 -87.663952                    0   

        1st Most Common Venue  2nd Most Common Venue  \
0          Mexican Restaurant             

In [59]:
chicago_merged.loc[chicago_merged['Cluster Labels New2'] == 1, chicago_merged.columns[[1] + list(range(5, chicago_merged.shape[1]))]]

2017 Population  Longitude  Cluster Labels New2 1st Most Common Venue  \
52             7394 -87.605344                    1        Clothing Store   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
52                 Field         Event Service               Exhibit   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
52            Eye Doctor           Fabric Shop                  Farm   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
52        Farmers Market  Fast Food Restaurant            Yoga Studio

In [60]:
chicago_merged.loc[chicago_merged['Cluster Labels New2'] == 2, chicago_merged.columns[[1] + list(range(5, chicago_merged.shape[1]))]]

2017 Population  Longitude  Cluster Labels New2 1st Most Common Venue  \
24            95260 -87.764851                    2                  Park   
45             2254 -87.596714                    2                  Park   
51            27742 -87.637823                    2     Convenience Store   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
24          Intersection    Athletics & Sports         Grocery Store   
45          Intersection                 Motel         Train Station   
51        Clothing Store         Grocery Store         Train Station   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
24           Flea Market           Fish Market           Flower Shop   
45           Bus Station        Farmers Market         Event Service   
51                  Park        Discount Store                  Bank   

   8th Most Common Venue       9th Most Common Venue 10th Most Common Venue  
24     Fish & Chips Shop         Filipino Restaurant                  Field  
45               Exhibit                  Eye Doctor            Fabric Shop  
51          Burger Joint  Construction & Landscaping                  Field

In [61]:
chicago_merged.loc[chicago_merged['Cluster Labels New2'] == 3, chicago_merged.columns[[1] + list(range(5, chicago_merged.shape[1]))]]

2017 Population  Longitude  Cluster Labels New2 1st Most Common Venue  \
49            14614 -87.571703                    3            Bike Trail   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
49        Waste Facility           Yoga Studio                 Field   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
49         Event Service               Exhibit            Eye Doctor   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
49           Fabric Shop                  Farm         Farmers Market

In [62]:
chicago_merged.loc[chicago_merged['Cluster Labels New2'] == 4, chicago_merged.columns[[1] + list(range(5, chicago_merged.shape[1]))]]

2017 Population  Longitude  Cluster Labels New2 1st Most Common Venue  \
48             6613 -87.598299                    4      Football Stadium   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
48        Discount Store        Clothing Store  Fast Food Restaurant   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
48         Event Service               Exhibit            Eye Doctor   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
48           Fabric Shop                  Farm         Farmers Market

It looks like the k-means clustering produced a significant clustering in the first cluster with approximately 70 communities while the other 4 clusters comprised only 6 communities in the aggregate. This helps to remove some communities but doesn't actually offer any significant reduc

### In this next section, we will analyze which communities have Coffee Shop in their top 4 venues.

In [63]:
chicago_merged

Community  2017 Population Area (sq mi)  \
0              Rogers Park, Chicago            55062         1.84   
1               West Ridge, Chicago            76215         3.53   
2                   Uptown, Chicago            57973         2.32   
3           Lincoln Square, Chicago            41715         2.56   
4             North Center, Chicago            35789         2.05   
5                Lake View, Chicago           100470         3.12   
6             Lincoln Park, Chicago            67710         3.16   
7          Near North Side, Chicago            88893         2.74   
8              Edison Park, Chicago            11605         1.13   
9             Norwood Park, Chicago            37089         4.37   
10          Jefferson Park, Chicago            26808         2.33   
11             Forest Glen, Chicago            19019         3.20   
12              North Park, Chicago            18842         2.52   
13             Albany Park, Chicago            51992         1.92   
14            Portage Park, Chicago            64307         3.95   
15             Irving Park, Chicago            54606         3.21   
16                 Dunning, Chicago            43689         3.72   
17               Montclare, Chicago            13830         0.99   
18          Belmont Cragin, Chicago            79910         3.91   
19                 Hermosa, Chicago            24144         1.17   
20                Avondale, Chicago            37368         1.98   
21            Logan Square, Chicago            73046         3.59   
22           Humboldt Park, Chicago            56427         3.60   
23               West Town, Chicago            84502         4.58   
24                  Austin, Chicago            95260         7.15   
25      West Garfield Park, Chicago            17163         1.28   
26      East Garfield Park, Chicago            19996         1.93   
27          Near West Side, Chicago            62872         5.69   
28          North Lawndale, Chicago            35947         3.21   
29          South Lawndale, Chicago            74851         4.59   
30         Lower West Side, Chicago            32888         2.93   
31         Near South Side, Chicago            23620         1.78   
32           Armour Square, Chicago            13455         1.00   
33                 Douglas, Chicago            20781         1.65   
34                 Oakland, Chicago             6645         0.58   
35             Fuller Park, Chicago             2439         0.71   
36         Grand Boulevard, Chicago            22313         1.74   
37                 Kenwood, Chicago            17189         1.04   
38         Washington Park, Chicago            11502         1.52   
39               Hyde Park, Chicago            26827         1.61   
40                Woodlawn, Chicago            23268         2.07   
41             South Shore, Chicago            50418         2.93   
42                 Chatham, Chicago            31120         2.95   
43             Avalon Park, Chicago             9985         1.25   
44           South Chicago, Chicago            28263         3.34   
45                Burnside, Chicago             2254         0.61   
46         Calumet Heights, Chicago            13188         1.75   
47                Roseland, Chicago            42433         4.82   
48                 Pullman, Chicago             6613         2.12   
49           South Deering, Chicago            14614        10.90   
50               East Side, Chicago            23737         2.98   
51            West Pullman, Chicago            27742         3.56   
52               Riverdale, Chicago             7394         3.53   
53               Hegewisch, Chicago             9418         5.24   
54          Garfield Ridge, Chicago            36396         4.23   
55          Archer Heights, Chicago            13142         2.01   
56           Brighton Park, Chicago            44813         2.72   
57           McKinley Pa

In [64]:
chi_coffeetop4 = chicago_merged[chicago_merged['1st Most Common Venue'].str.contains('Coffee') | chicago_merged['2nd Most Common Venue'].str.contains('Coffee') | chicago_merged['3rd Most Common Venue'].str.contains('Coffee') | chicago_merged['4th Most Common Venue'].str.contains('Coffee')]
chi_coffeetop4

Community  2017 Population Area (sq mi)  \
2            Uptown, Chicago            57973         2.32   
4      North Center, Chicago            35789         2.05   
7   Near North Side, Chicago            88893         2.74   
10   Jefferson Park, Chicago            26808         2.33   
12       North Park, Chicago            18842         2.52   
15      Irving Park, Chicago            54606         3.21   
21     Logan Square, Chicago            73046         3.59   
36  Grand Boulevard, Chicago            22313         1.74   
39        Hyde Park, Chicago            26827         1.61   
57    McKinley Park, Chicago            15767         1.41   
74           O'Hare, Chicago            12377        13.34   
75        Edgewater, Chicago            55965         1.74   

    2017 Population Density (/sq mi)   Latitude  Longitude  \
2                           24988.36  41.966630 -87.655546   
4                           17458.05  41.956107 -87.679160   
7                           32442.70  41.900033 -87.634497   
10                          11505.58  41.969738 -87.763118   
12                           7476.98  41.984955 -87.722933   
15                          17011.21  41.953365 -87.736447   
21                          20347.08  41.928568 -87.706793   
36                          12823.56  41.813923 -87.617272   
39                          16662.73  41.794225 -87.592562   
57                          11182.27  41.831700 -87.673664   
74                            927.81  41.973101 -87.906768   
75                          32163.79  41.983369 -87.663952   

    Cluster Labels New2 1st Most Common Venue  2nd Most Common Venue  \
2                     0           Coffee Shop  Vietnamese Restaurant   
4                     0                   Bar            Coffee Shop   
7                     0           Coffee Shop             Steakhouse   
10                    0                   Bar               Pharmacy   
12                    0                  Park            Coffee Shop   
15                    0                   Bar            Coffee Shop   
21                    0                   Bar            Coffee Shop   
36                    0           Coffee Shop           Liquor Store   
39                    0           Coffee Shop         Sandwich Place   
57                    0           Coffee Shop             Donut Shop   
74                    0        Airport Lounge            Coffee Shop   
75                    0        Sandwich Place            Coffee Shop   

   3rd Most Common Venue 4th Most Common Venue      5th Most Common Venue  \
2            Pizza Place    Chinese Restaurant                      Diner   
4     Mexican Restaurant                   Pub         Chinese Restaurant   
7                  Hotel                   Gym                        Bar   
10                  Park           Coffee Shop         Chinese Restaurant   
12        Sandwich Place           Bus Station       Kitchen Supply Store   
15                   Gym        Sandwich Place                Pizza Place   
21          Cocktail Bar                  Café  Latin American Restaurant   
36             BBQ Joint         Train Station                Art Gallery   
39                  Café             Bookstore                Pizza Place   
57           Video Store           Gas Station                      Diner   
74           Snack Place       Airport Service          Accessories Store   
75                Bakery    Mexican Restaurant         Italian Restaurant   

          6th Most Common Venue 7th Most Common Venue  \
2                           Bar       Thai Restaurant   
4                       Brewery           Pizza Place   
7                   Pizza Place    Italian Restaurant   
10  Eastern European Restaurant           Video Store   
12               Gymnastics Gym      Department Store   
15            Convenience Store            Donut Shop   
21                  Pizza Place           Art Gallery   
36        

This gives us a list of about a dozen neighborhoods to begin looking at. We really want to look for communities where Coffee Chop is in the top 1 or 2 ideally, and possibly other venues shuch as Cafe and Donut Shop are also in the top handful of venues.

The following do not appear to have Coffee Shop or other relevant categories in the top few categories and will be eliminated:

- #10 Jefferson Park - Coffee Shop is not in the top few venues and the top venues do not align with retail we are looking for
- #40 Woodlawn - Coffee Shop is not in the top few venues and the top venues do not align with retail we are looking for (Note Woodlawn was in previous runs but on some runs of the program it odes not appear at all)
- #67 Englewood - Coffee Shop is not in the top few venues and the top venues do not align with retail we are looking for (Note Englewood was in previous runs but on some runs of the program it odes not appear at all)
- #74 O'Hare - We do not want to be near an airport

This reduces our list somewhat with the remaining having Coffee Shop as their number 1 or number 2 venue, and multiple communities also having Cafe, Bookstore, Donut Shop or Bakery as their top venues as well


In [65]:
chi_nearfinal = chi_coffeetop4.drop([10,74])
chi_nearfinal

Community  2017 Population Area (sq mi)  \
2            Uptown, Chicago            57973         2.32   
4      North Center, Chicago            35789         2.05   
7   Near North Side, Chicago            88893         2.74   
12       North Park, Chicago            18842         2.52   
15      Irving Park, Chicago            54606         3.21   
21     Logan Square, Chicago            73046         3.59   
36  Grand Boulevard, Chicago            22313         1.74   
39        Hyde Park, Chicago            26827         1.61   
57    McKinley Park, Chicago            15767         1.41   
75        Edgewater, Chicago            55965         1.74   

    2017 Population Density (/sq mi)   Latitude  Longitude  \
2                           24988.36  41.966630 -87.655546   
4                           17458.05  41.956107 -87.679160   
7                           32442.70  41.900033 -87.634497   
12                           7476.98  41.984955 -87.722933   
15                          17011.21  41.953365 -87.736447   
21                          20347.08  41.928568 -87.706793   
36                          12823.56  41.813923 -87.617272   
39                          16662.73  41.794225 -87.592562   
57                          11182.27  41.831700 -87.673664   
75                          32163.79  41.983369 -87.663952   

    Cluster Labels New2 1st Most Common Venue  2nd Most Common Venue  \
2                     0           Coffee Shop  Vietnamese Restaurant   
4                     0                   Bar            Coffee Shop   
7                     0           Coffee Shop             Steakhouse   
12                    0                  Park            Coffee Shop   
15                    0                   Bar            Coffee Shop   
21                    0                   Bar            Coffee Shop   
36                    0           Coffee Shop           Liquor Store   
39                    0           Coffee Shop         Sandwich Place   
57                    0           Coffee Shop             Donut Shop   
75                    0        Sandwich Place            Coffee Shop   

   3rd Most Common Venue 4th Most Common Venue      5th Most Common Venue  \
2            Pizza Place    Chinese Restaurant                      Diner   
4     Mexican Restaurant                   Pub         Chinese Restaurant   
7                  Hotel                   Gym                        Bar   
12        Sandwich Place           Bus Station       Kitchen Supply Store   
15                   Gym        Sandwich Place                Pizza Place   
21          Cocktail Bar                  Café  Latin American Restaurant   
36             BBQ Joint         Train Station                Art Gallery   
39                  Café             Bookstore                Pizza Place   
57           Video Store           Gas Station                      Diner   
75                Bakery    Mexican Restaurant         Italian Restaurant   

   6th Most Common Venue 7th Most Common Venue     8th Most Common Venue  \
2                    Bar       Thai Restaurant             Grocery Store   
4                Brewery           Pizza Place       American Restaurant   
7            Pizza Place    Italian Restaurant            Clothing Store   
12        Gymnastics Gym      Department Store              Soccer Field   
15     Convenience Store            Donut Shop           Border Crossing   
21           Pizza Place           Art Gallery        Mexican Restaurant   
36             Jazz Club                Lounge                Restaurant   
39       Thai Restaurant                   Spa  Mediterranean Restaurant   
57    Mexican Restaurant           Bus Station        Chinese Restaurant   
75      Sushi Restaurant          Burger Joint                   Theater   

     9th Most Common Venue 10th Most Common Venue  
2         Sushi Restaurant     Mexican Restaurant  
4             Dessert Shop                   Bank  
7                  

Next I will compare the population density of these 9 communities to see if there is any specific data to help reduce our list further. We can see in the table above that the population density varies greatly

In [66]:
chi_nearfinal.describe()

2017 Population  2017 Population Density (/sq mi)   Latitude  \
count        10.000000                         10.000000  10.000000   
mean      45002.100000                      19255.673000  41.911287   
std       24860.920656                       8398.769576   0.072578   
min       15767.000000                       7476.980000  41.794225   
25%       23441.500000                      13783.352500  41.848783   
50%       45197.500000                      17234.630000  41.940967   
75%       57471.000000                      23828.040000  41.963999   
max       88893.000000                      32442.700000  41.984955   

       Longitude  Cluster Labels New2  
count  10.000000                 10.0  
mean  -87.668283                  0.0  
std     0.045852                  0.0  
min   -87.736447                  0.0  
25%   -87.699885                  0.0  
50%   -87.668808                  0.0  
75%   -87.639760                  0.0  
max   -87.592562                  0.0

In [67]:
# We can also present the population density visually:
boxplot = chi_nearfinal.boxplot(column=['2017 Population Density (/sq mi)'])
boxplot

We can see the mean population density is 19,256 while min and max of our selected communities are 7,477 & 32,443 respectively with a standard deviation of 8,399. Our client has already determined through prior research and experience that higher than average population density is key to generating a vibrant atmosphere with ongoing foot traffic

We can now see from the table that two communities have population densities above 1 standard deviation (mean 19,256 + std 8,399 = 27,655): Near North Side and Edgewater. Uptown comes close being outside the 75% range but just under 1 std.